# Generated by Django 4.0.5 on 2022-07-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
