# Generated by Django 4.0.5 on 2022-07-22 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_remove_users_confirmpassword'),
    ]

    operations = [
        # migrations.AddField(
            # model_name='blogs',
            # name='UserId',
            # field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.users'),
            # preserve_default=False,
        # ),
    ]
