# Generated by Django 4.0.5 on 2022-07-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_blogs_userid'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='blogs',
        #     name='UserId',
        # ),
    ]
