# Generated by Django 4.0.5 on 2022-07-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_remove_blogs_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='UserId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.users'),
            preserve_default=False,
        ),
    ]
