# Generated by Django 4.0.5 on 2022-07-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_blogs_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='pub_date',
        ),
    ]
