# Generated by Django 4.0.5 on 2022-07-26 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_remove_blogs_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
