# Generated by Django 4.0.5 on 2022-07-26 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_blogs_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=400)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 7, 26, 12, 44, 52, 935472, tzinfo=utc), verbose_name='Date created')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.users')),
            ],
        ),
    ]
