# Generated by Django 4.0.5 on 2022-07-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_alter_comment_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
