# Generated by Django 4.0.5 on 2022-07-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_users_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='UserMail',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
