# Generated by Django 4.0.5 on 2022-08-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
